//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linq.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int MarksID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> StandardID { get; set; }
        public Nullable<int> MarksObtained { get; set; }
        public Nullable<int> TotalMarks { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
